services:
  barber-shop-ui:
  build:
    context: ./ui 
    dockerfile: Dockerfile
  container_name: barber-shop-ui
  ports:
    - "80:80"
  networks:
    - barber-shop-network
  restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  barber-shop-network:
    external: true
